clienteVendedor: main.cpp Persona.cpp Vendedor.cpp Cliente.cpp
	g++ main.cpp Persona.cpp Vendedor.cpp Cliente.cpp -o clienteVendedor

	cd /Users/alejandronieto/Desktop/Compartida/PR
	git add .
	git commit -m "Cambio"
	git push -u origin master
